import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { getUser } from '@/lib/db/queries'
import { UserProvider } from '@/lib/auth'
import { User } from '@/lib/db/types'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  let userPromise = getUser()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider userPromise={userPromise as Promise<User | null>}>
          <div className="w-full min-h-screen bg-secondary">
            <div className="w-[400px] h-[400px] absolute bottom-[100px] left-[300px] ml-[-100px] bg-primary blur-[100px] rounded-full opacity-50"></div>
            {children}
          </div>
        </UserProvider>
      </body>
    </html>
  )
}
